"""Initial migration with all tables

Revision ID: 6d5b2425ca32
Revises: 
Create Date: 2025-09-18 01:12:39.144541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5b2425ca32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_index(op.f('ix_videos_filename'), 'videos', ['filename'], unique=False)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_table('trimmed_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_video_id', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['original_video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_index(op.f('ix_trimmed_videos_id'), 'trimmed_videos', ['id'], unique=False)
    op.create_table('video_qualities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_video_id', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['original_video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_index(op.f('ix_video_qualities_id'), 'video_qualities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_qualities_id'), table_name='video_qualities')
    op.drop_table('video_qualities')
    op.drop_index(op.f('ix_trimmed_videos_id'), table_name='trimmed_videos')
    op.drop_table('trimmed_videos')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_filename'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###